### ISSUE TITLE
use where in output query

### ISSUE THREAD

**Issue by mostafaznv** [atayahmet/laravel-nestable#1]
hi.
thanks for your nice package.

i created a custom database like this:

| id 	| parent_id 	| name   	| slug  	| post_type 	| img        	|
|----	|-----------	|--------	|-------	|-----------	|------------	|
| 1  	| 0         	| cat 1  	| cat-1 	| posts     	| thumb.jpg  	|
| 2  	| 1         	| cat 2  	| cat-2 	| posts     	| p.png      	|
| 3  	| 0         	| cat 3  	| cat-3 	| products  	| pthumb.jpg 	|

i want to show only categories for a specific post_type 
can u help me?

**Comment by mostafaznv** [comment]
i can override get() in NestableTrait.php like this:
```
$this->source = parent::where('post_type','posts')->get();
```
but if i update the package, all these will gone...

**Comment by mostafaznv** [comment]
i created NestableTraitPlus 
now i use my own functions and i think it's a safe way ...

**Comment by atayahmet** [comment]
Hi Mostafa,

I have seen yet the message. Let me check.

**Comment by atayahmet** [comment]
That missing the **->nested()** method in your query.

**Comment by mostafaznv** [comment]
thank you dear ahmet...
so it's a safe way to create "NestableTraitPlus" and using new get() function?

or if i should wait for new version, how long does it take?

**Comment by atayahmet** [comment]
Hi @mostafaznv 

it's fixed: [96cac5a](https://github.com/atayahmet/laravel-nestable/commit/96cac5aa16755e9026cc5f1b0ba1dace0a1d6cad) 
You should update the package.

**Comment by mostafaznv** [comment]
thanks ...
it works fine only for nested()
but i get these errors for other methods (renderAsDropdown, renderAsHtml):
`Call to a member function where() on string`
`Call to a member function get() on string`

**Comment by atayahmet** [comment]
Hi @mostafaznv 

Please use such: `Category::where('post_type', 'posts')->renderAsHtml();`
or
`Category::where('post_type', 'posts')->renderAsDropdown();`

Not use such:
`Category::where('post_type', 'posts')->renderAsDropdown()->get();`

**Comment by mostafaznv** [comment]
but it return all records in my table
`$categories = category::where('post_type', 'posts')->renderAsHtml();`

**Comment by atayahmet** [comment]
I tested the changes and works fine. Are you share the results?

**Comment by mostafaznv** [comment]
this is my table:
![](http://8pic.ir/images/ogpgzn5tomb19rxet8me.png?raw=true)
i get below result with this code: 
```
$categories = \App\category::where('post_type', 'posts')->renderAsHtml();
return $categories;
```
![](http://8pic.ir/images/okhdbivk71n22vpugdel.png?raw=true)

**Comment by atayahmet** [comment]
Hi @mostafaznv 

update and try again.

**Comment by mostafaznv** [comment]
wow ...
thanks dear ahmet ...
it works fine ...

**Comment by atayahmet** [comment]
Thank you too for contribution @mostafaznv .
