### ISSUE TITLE
Any way to make renderAsDropdown() work with form model binding?

### ISSUE THREAD

**Issue by ashish64** [atayahmet/laravel-nestable#10]
Im running circles here... please help. How can i make this work with form model binding with existing data?

**Comment by ashish64** [comment]
More info:
Im using this Category::selected(1)->renderAsDropdown();
but it is giving me result of renderAsMultiple(); without any selection.

**Comment by atayahmet** [comment]
Hİ @ashish64 

please check this section: [make()](https://github.com/atayahmet/laravel-nestable#using-independent-models)
