### ISSUE TITLE
integration of Jquery nestable to your package

### ISSUE THREAD

**Issue by aghayeff** [atayahmet/laravel-nestable#12]
Have you thought that integrate Jquery nestable to your package? 

[Jquery Nestable](http://dbushell.github.io/Nestable/)

I tried to make it workable, but there is some missed things in your package. 
1 ) Using `<ol>` instead of `ul`
2) Adding `data-id` attribute to `<li>`. For example:
`<li data-id=1>Label</li>`

**Comment by jinhongjie007** [comment]
I also encountered this problem

**Comment by johannesschobel** [comment]
In my opinion it is not good to "tie these packages together", as you will need to maintain additional dependencies and it might not be needed in a lot of projects.

I would suggest to add a new project (which can be also installed via composer) to add the desired features. I think, the package itself should be striped down to its core - providing nestable models and output them in a generic data structure (e.g., arrays or json). The other features (e.g., show them as list, or dropdown, ...) should not be provided by this package but within another one.

For me, building only an API, it is completely unneccessary to have a HTML view, as this must be done by the frontend project (e.g., angular, vue, ...)
