### ISSUE TITLE
Generating deep url for sub categories

### ISSUE THREAD

**Issue by aghayeff** [atayahmet/laravel-nestable#13]
Well, lets look through this example:

```
<ul>
    <li><a href="">T-shirts
        <ul>
            <li><a href="red-t-shirt">Red T-shirt</a>
                <ul>
                     <li><a href="s-size">S size</a><li>
                     <li><a href="m-size">M size</a><li>
                     <li><a href="l-size">L size</a><li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
```

Is it possible to generate **deep url** for sub categories? 

Instead of 
`<li><a href="s-size">S size</a><li>`

generate
`<li><a href="red-t-shirt/s-size">S size</a><li>`

**Comment by atayahmet** [comment]
Hi @aghayeff 

I added new feature via your suggestion. Now passed parent element to closure function. If has not parent element of current elements is passed `null`, Please update package.

Example:
```php
<?php

Menu::route(function($href, $label, $parent) {

    return \URL::to($href);

})->renderAsHtml();
```

**Comment by aghayeff** [comment]
Thanks!  I appreciate
