### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by aghict** [atayahmet/laravel-nestable#15]
Hello,
When I want to use this package I get:

Fatal error: Out of memory (allocated 1470103552) (tried to allocate 262144 bytes) in D:\xampp\htdocs\platform\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 621

After remove Nestable\NestableServiceProvider::class problem fixed.

Now How can I use this package.

Note:I change my memory_limit but yet it need more memory.

**Comment by atayahmet** [comment]
Hello @aghict 

I have never encountered such a problem before. Please send example code you used.

**Comment by aghict** [comment]
Hello,
I don't use it just I add in app service provider.

**Comment by atayahmet** [comment]
Hello again,

When i test it  that did not get any memory error. Please check other package dependencies the your project.

**Comment by aghict** [comment]
Hello,
I attached my composer.json 
Please check it for me.
[composer.zip](https://github.com/atayahmet/laravel-nestable/files/768625/composer.zip)

**Comment by atayahmet** [comment]
There is no my package in `composer.json`. Everything is normal except.

**Comment by aghict** [comment]
Yes,
I remove it because memory over load.
I think there is conflict with other packages just test it.

**Comment by atayahmet** [comment]
Very interesting case. Package Service Provider is not complicated. 

Please check: [ServiceProvider](https://github.com/atayahmet/laravel-nestable/blob/master/src/NestableServiceProvider.php) (you have already checked)

**Comment by aghict** [comment]
I don't understand what should I do?

**Comment by atayahmet** [comment]
There is nothing I can say in this regard. The problem is not in the package can be in your development environment. Try again in a different environment.
