### ISSUE TITLE
where is breadcrumb option, how i can retrieve parents of child?

### ISSUE THREAD

**Issue by knour89** [atayahmet/laravel-nestable#16]
hello i want to inverse the hierarchy, since each child can have one parent, how i can retrieve the breadcrumb (parents) of a child?

-Electornic
--Computer and tablet
---Computer (want get parent of computer as below)

i want below
Compiter > Computers and Tablets > Electronic

**Comment by atayahmet** [comment]
Hi @knour89 

This package exports only array, json and html snippets.  But for now. if give me little bit time, i will can add your asked feature. Of course, if this feature is urgent you can find another very usefully packages for this.

Most known: [laravel-breadcrumbs](https://github.com/davejamesmiller/laravel-breadcrumbs)

**Comment by knour89** [comment]
thx for your respond, i will for your new update

**Comment by atayahmet** [comment]
Your welcome. Alikom slamo brother.

**Comment by johannesschobel** [comment]
i will take a look at this issue this / next week.. i will contribute to this package by providing different URIs for the categories and then fix this issue as well..

**Comment by kjareena** [comment]
Hi @knour89 atayahmet

I am waiting for your reply. Please suggest me ASAP.

**Comment by MiselAdemi** [comment]
Here is my solution function for breadcrumb:

```
protected $parents = array();

public function parent_cat($cat) {
      if ($cat->parent_id > 0) {
        $this->parents[] = Category::find($cat->parent_id);
        self::parent_cat(Category::find($cat->parent_id));
      }
      return $this->parents;
    }
```

**Comment by kjareena** [comment]
Thanks
