### ISSUE TITLE
i just want a documentation for this bieutifull package

### ISSUE THREAD

**Issue by amine8ghandi8amine** [atayahmet/laravel-nestable#17]
i dont know when to write some things

like those basic things

*************************************

use Nestable\NestableTrait;

class Category extends \Eloquent {

    use NestableTrait;

    protected $parent = 'parent_id';

}
Note: $parent variable refers to the parent category (Default parent_id)
<?php

$categories = Category::nested()->get();

**Comment by atayahmet** [comment]
Hi @amine8ghandi8amine 

Sorry, i dont understand you. What's the problem exactly?
