### ISSUE TITLE
configuring the link, route

### ISSUE THREAD

**Issue by amine8ghandi8amine** [atayahmet/laravel-nestable#20]
hi i have many nested categories like mechanic-part,car and place but when i render as html and i click in a link it go directly to site.local/{slug}
i want to change to custom link like site.local/car/{slug} site.local/mechanic-part/{slug} .... how can i?

**Comment by amine8ghandi8amine** [comment]
how can i do dat?

**Comment by johannesschobel** [comment]
i think, it is currently not available.. however, i will take a look at it later on.. i will try to give feedback until next week..

**Comment by amine8ghandi8amine** [comment]
thank you johannesschobel because it is important to work with

**Comment by atayahmet** [comment]
Hi @amine8ghandi8amine 

Sorry for my late answer. I am working hard these days so i do not have enough time. If @johannesschobel fix the issue i accept PR.

**Comment by atayahmet** [comment]
Hi again

i added that feature. Please check: [customUrl](https://github.com/atayahmet/laravel-nestable#customurl)

**Comment by amine8ghandi8amine** [comment]
ow Thank you man you are right you work hard
