### ISSUE TITLE
One more thing Some featur need to work with attribute like customUrl()

### ISSUE THREAD

**Issue by amine8ghandi8amine** [atayahmet/laravel-nestable#21]
and a lot of feature just ulAttr() that work nice with attribute how can i ?

AND HOW THE RIGHT WAY TO UPDATE THE PACKAGE CAUSE MY COMPOSER DONT FIND THE customUrl()

**Comment by atayahmet** [comment]
Remove package and clean composer cache then install package again.

**Comment by amine8ghandi8amine** [comment]
thank you man its WORK i want to do something like you one day
