### ISSUE TITLE
Output in 3 columns

### ISSUE THREAD

**Issue by Yadziro** [atayahmet/laravel-nestable#23]
Hi guys! This is a great library! Tell me how I can output this style:

page:
```
Category 1         | Category 4         | Category 7
Subcategories 1    | Subcategories 4    | Subcategories 7
Category 2         | Category 5         | Category 8
Subcategories 2    | Subcategories 5    | Subcategories 8
Category 3         | Category 6         | Category 9
Subcategories 3    | Subcategories 6    | Subcategories 9
```

**Comment by Yadziro** [comment]
Thank you, already done. ;-)

**Comment by atayahmet** [comment]
Hi @Yadziro,  your welcome :)

**Comment by MahmoudAdham** [comment]
Hi, 
Thank you for this package,
I want to add now filed form my database table, I did change in  nested.php but not show new field,
can you please tell me how can I do it?
