### ISSUE TITLE
Undefined index: 

### ISSUE THREAD

**Issue by bijondev** [atayahmet/laravel-nestable#28]
hi, I am trying to use your packeg. But its showing flowing error.
![screenshot_9](https://user-images.githubusercontent.com/4652432/29453032-1718a2aa-842a-11e7-96c5-54d30ce8a2f4.png)
And my Table structure is 
![screenshot_8](https://user-images.githubusercontent.com/4652432/29453056-29166406-842a-11e7-8264-9680f2b28ae8.png)

please help....

**Comment by roballport** [comment]
You need to set the correct values as the package read me suggests. The default column it looks for is ```name```. As you have the column ```title``` you're seeing the error.

After publishing ```https://github.com/atayahmet/laravel-nestable/blob/master/config/nestable.php``` adjust the values to be in line with your database structure.

**Comment by atayahmet** [comment]
Thanks @roballport  for detailed description.
