### ISSUE TITLE
orderBy not working with pagination

### ISSUE THREAD

**Issue by Miri92** [atayahmet/laravel-nestable#30]
orderBy() default showing "asc". Desc not working. Laravel version 5.3.
$categories = Category::orderBy('id', 'desc')->paginate(15);

**Comment by atayahmet** [comment]
Hi @Miri92, 

I have not enough time for fix it. Please remove `NestableTrait` interface from `Category` model. Use [nestable()](https://github.com/atayahmet/laravel-nestable#helper) helper as workaround.
