### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vplanes** [atayahmet/laravel-nestable#32]
Hi,
I'm trying to install the package in Laravel 5.1.46 but I get this error:

composer require atayahmet/laravel-nestable
Using version ^0.8.1 for atayahmet/laravel-nestable
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for atayahmet/laravel-nestable ^0.8.1 -> satisfiable by atayahmet/laravel-nestable[v0.8.1].
    - Conclusion: remove laravel/framework v5.1.46
    - Conclusion: don't install laravel/framework v5.1.46
    - atayahmet/laravel-nestable v0.8.1 requires illuminate/database 5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by illuminate/database[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.2].
    - don't install illuminate/database v5.2.0|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.19|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.21|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.24|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.25|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.26|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.27|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.28|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.31|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.32|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.37|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.43|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.45|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.6|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.2.7|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.3.0|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.3.16|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.3.23|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.3.4|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.13|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.17|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.19|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.27|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.36|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.4.9|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.5.0|don't install laravel/framework v5.1.46
    - don't install illuminate/database v5.5.2|don't install laravel/framework v5.1.46
    - Installation request for laravel/framework ~5.1.46 -> satisfiable by laravel/framework[v5.1.46].

Installation failed, reverting ./composer.json to its original content.

Where is the problem?
Thanks!

**Comment by atayahmet** [comment]
Hi @vplanes 

only support Laravel 5.2 and after versions. Your version 5.1
