### ISSUE TITLE
Apply formatting to just children?

### ISSUE THREAD

**Issue by gracedigital** [atayahmet/laravel-nestable#38]
If I change the prefix in the nestable.php file it applies it to all options in the list.  Is it possible to have it only apply the prefix to just children?

    'dropdown' => [
        'prefix' => ' - ',
        'label' => 'name',
        'value' => 'id'
    ]

![screen shot 2017-12-06 at 11 15 17 am](https://user-images.githubusercontent.com/13338159/33680646-24a2c628-da77-11e7-8882-bb22cbca59aa.png)

**Comment by atayahmet** [comment]
Hi @gracedigital 

Not possible. Applies to all options.
