### ISSUE TITLE
$categories = Category::nested()->get();

### ISSUE THREAD

**Issue by shrikanth003** [atayahmet/laravel-nestable#39]
Im using laravel 5.5. I have added the package. I have also added the trait to the model,

Where do i need to specify this $categories = Category::nested()->get();
When i do {{$categories = Category::nested()->get();}} it does not show anything on the view

**Comment by atayahmet** [comment]
Hi @shrikanth003 

`->nested()` method will return array tree. If you want use in html template, you have to choose a render method. 

Example: 

```php
{{ Category::renderAsHtml() }}
```
or:

```php
{{ Category:: renderAsDropdown() }}
```

**Comment by shrikanth003** [comment]
Ok. Is theere any tutorial on this? I mean on how to create a nested categories list with Dependent dropdown

**Comment by atayahmet** [comment]
I think this section will be helpfuly: [Render as dropdown](https://github.com/atayahmet/laravel-nestable#renderasdropdownrenderasmultiple)

**Comment by shrikanth003** [comment]
My Categories Model Looks Like this
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Nestable\NestableTrait;

class Category extends Model
{
  use NestableTrait;
  protected $parent = 'parent_id';
}

My Categories Table looks like id, parent_id, name, slug

I have placed {{Category::renderAsHtml()}} on my Website index page.

My Controller looks like this
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class PagesController extends Controller
{
    /**
    * Show the application dashboard.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $categories = Category::nested()->get();
        return view('index');
    }    
}

I'm a learner and didn't find any proper tutorial on this. Could you correct me or help me understanding how this works. @atayahmet

**Comment by shrikanth003** [comment]
Because i get a error Class 'Category' not found (View: D:\xampp\htdocs\myproject\resources\views\index.blade.php)

**Comment by atayahmet** [comment]
Ok.The default path for models is the `app` directory

You can call this way:
```php
{{ \App\Category::renderAsHtml() }}
```

But if you want to call with direct model name, run the command below:

Terminal:
```sh
$ composer dump-autoload
```

Now you can use this way:
```php
{{ Category::renderAsHtml() }}
```

**Comment by shrikanth003** [comment]
It worked! Tysm :)
