### ISSUE TITLE
PHP 7.2.0 Issue on NestableService.php

### ISSUE THREAD

**Issue by wakamin** [atayahmet/laravel-nestable#40]
I upgrade to PHP 7.2.0 and facing this error

**count(): Parameter must be an array or an object that implements Countable on vendor/atayahmet/laravel-nestable/src/Services/NestableService.php line 406**

Then to fix this, I change this

```
if (count(func_num_args()) < 3) {
    $data = $this->data;
    $key = $this->parent;
    $value = current(func_get_args());
}
```
into this

```
if (func_num_args() < 3) {
    $data = $this->data;
    $key = $this->parent;
    $value = current(func_get_args());
}
```

Let me know if there is a better solution. Thanks.

**Comment by atayahmet** [comment]
Hi @wakamin 

Fixed. Thank you for contribution. Update the package.
