### ISSUE TITLE
renderAsDropdown Getting white page 

### ISSUE THREAD

**Issue by kjareena** [atayahmet/laravel-nestable#44]
Hi Atayahmet,

I Am  using atayahmet/laravel-nestable plug.

As per document i installed your package everything is fine but i want my categories in drop down.
 For that i used like 

                        EventCategory::attr(['name' => 'categories'])
                            ->selected(1)
                            ->renderAsDropdown(); 
in my view file its getting white page.

I am using laravel5.5 and php 7 versions

Please suggest me where i did mistake.

Thanks in advance.

**Comment by kjareena** [comment]
I have solved this issue.

This issue caused because i did not set **parent_id** as a for foreign key of main **id**.

Please suggest me how i set default " Select one " empty value in dropdown

**Comment by josegus** [comment]
Maybe you could return first as array, then use nestable() helpers with ->make()
