### ISSUE TITLE
Multiple dropdowns using 'nestable($data)'

### ISSUE THREAD

**Issue by palo** [atayahmet/laravel-nestable#46]
I'm trying to render multiple dropdowns from level 0 categories, like so: 

`$categories = Category::nested()->get();`

```
@foreach ( $categories as $category )
{!! nestable($category)->renderAsDropdown() !!}
@endforeach
```
But getting this error: "Illegal string offset 'parent_id'"..

If i pass it like this: 
```
@foreach ( $categories as $category )
{!! nestable($category['child'])->renderAsDropdown() !!}
@endforeach
```
It renders empty dropdowns

Can you please explain how to achieve this?

**Comment by atayahmet** [comment]
Hi @palo 

You can do it like this:

```php
@foreach ( $categories as $category )
{!! nestable([$category])->renderAsDropdown() !!}
@endforeach
```

**Comment by palo** [comment]
Thank you
