### ISSUE TITLE
Category by Id

### ISSUE THREAD

**Issue by mifas** [atayahmet/laravel-nestable#48]
Example category table

| id | parent_id | name  | slug  |
|----|-----------|-------|-------|
| 1  | 0         | Car   | car   |
| 2  | 1         | BMW   | bmw   |
| 3  | 1         | Benz  | benz  |
| 4  | 0         | Truck | truck |

Is there any way to get Car's children only?

Current output. Truck category also return
```
{  
   "id":1,
   "name":"Car",
   "slug":"car",
   "child":[  
      {  
         "id":2,
         "name":"BMW",
         "slug":"bmw"
      },
      {  
         "id":3,
         "name":"Benz",
         "slug":"benz"
      }
   ]
},
{  
   "id":1,
   "name":"Truck",
   "slug":"truck"
}
```

**Comment by ultrono** [comment]
As per the documentation, see https://github.com/atayahmet/laravel-nestable#parent

**Comment by mifas** [comment]
That's not correct. Because I want ONLY Car's children. If I use `->parent(0)` then Truck records will also return

**Comment by atayahmet** [comment]
Hi @mifas 

There is no other way for now. You can fork it and send PR.

**Comment by mifas** [comment]
Thank you @atayahmet
