### ISSUE TITLE
I cannot use Eloquent methods

### ISSUE THREAD

**Issue by Mohamed-Zedan** [atayahmet/laravel-nestable#5]
Hello @atayahmet I've just installed your package to handle categories, but when I use Nestable\NestableTrait all Eloquent methods are not working as where(), findOrFail(), delete() ....
And if I remove NestableTrait everything working good. 

Any solutions please ..

**Comment by Mohamed-Zedan** [comment]
e.g. 
- code:
`
$category = Category::findOrFail(8);
dd($category);
`
The result is same even ID is wrong.
`
Category {#330 ▼
  #parent: "parent_id"
  #table: "categories"
  #fillable: array:6 [▼
    0 => "name"
    1 => "name_ar"
    2 => "description"
    3 => "description_ar"
    4 => "image"
    5 => "parent_id"
  ]
  #connection: null
  #primaryKey: "id"
  #keyType: "int"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: []
  #original: []
  #relations: []
  #hidden: []
  #visible: []
  #appends: []
  #guarded: array:1 [▼
    0 => "*"
  ]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: false
  +wasRecentlyCreated: false
  #source: null
}
`

**Comment by Mohamed-Zedan** [comment]
I think the __call method in NestableTrait that are causing the problem.

please help me @atayahmet

**Comment by atayahmet** [comment]
Hi @Mohamed-Zedan 

i fixed the problem. Please update the package and try again. 
Check the commit: [aae8fe5](https://github.com/atayahmet/laravel-nestable/commit/05633e2a8748ff7e64dfa908e61e7a960aae8fe5)

**Comment by Mohamed-Zedan** [comment]
Hello again @atayahmet 
It has been fixed.
But I got new problem with relations methods, and again __call method causing the problem.

Category model:
`
<?php

namespace Modules\Arinashop\Entities;

use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Model;
use Nestable\NestableTrait;

class Category extends Model {
    use Sluggable;
    use SluggableScopeHelpers;
    use NestableTrait;

    protected $parent = 'parent_id';

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable() {
        return [
            'slug' => [
                'source' => ['name', 'parentName.name'],
            ],
        ];
    }

    protected $table    = 'categories';
    protected $fillable = ['name', 'name_ar', 'description', 'description_ar', 'image', 'parent_id'];

    public function parentName() {
        return $this->belongsTo('Modules\Arinashop\Entities\Category', 'parent_id');
    }

    public function children() {
        return $this->hasMany('Modules\Arinashop\Entities\Category', 'parent_id');
    }

    public function products() {
        return $this->hasMany('Modules\Arinashop\Entities\Product', 'category_id', 'id');
    }

    public function tags() {
        $products = $this->hasMany('Modules\Arinashop\Entities\Product', 'category_id', 'id')->get();
        $tags     = array();

        foreach ($products as $product) {
            foreach ($product->tags as $tag) {
                $tags[] = $tag;
            }
        }

        return $tags;
    }

}

`

Problem is when I call any relations methods such as product() or children() after update package, these methods return all items from all categories. And again when I comment __call function it's works.

**Comment by atayahmet** [comment]
Hello @muhammed

This package is not designed with use relations.
You can use helper or macro way as alternative without NestableTrait.

**Comment by Mohamed-Zedan** [comment]
@atayahmet Ok I got it.. Thanks alot my friend :+1:

**Comment by Mohamed-Zedan** [comment]
@atayahmet Ok I got it.. Thanks alot my friend :+1:
