### ISSUE TITLE
Not Compatible With Laravel  5.6

### ISSUE THREAD

**Issue by zymawy** [atayahmet/laravel-nestable#53]
Hello Thank You For Your Time Making Good Work Out There 🔥 

I Have Installed The Package 📦 

On Laravel 5.6 💯 But It's Not Displaying When Using The Methods On Your Package 
I May Do Something Wrong

**Comment by ultrono** [comment]
I'm using this package with Laravel 5.6.15 without issue. You'll need to provide more details so people can help.

**Comment by ultrono** [comment]
Ah, just realized you'll need version 0.8.6 or above. It appears Laravel 5.6 was added then - https://github.com/atayahmet/laravel-nestable/commit/49668c3c78066b5d0da09b20979096e00abf72fd

I'd always recommend having a look at the releases pages and recent commits as all the information is there.

**Comment by zymawy** [comment]
Solved 💯

**Comment by ultrono** [comment]
@zymawy If possible please add your solution here to help other people.

**Comment by zymawy** [comment]
In My Category Migration File, I Was Using 
`$table->unsignedInteger('parent_id');`
Instead Of 
` $table->integer('parent_id')->unsigned();`
