### ISSUE TITLE
Laravel Controller ve View üzerinden gösterim

### ISSUE THREAD

**Issue by GkyKrkc** [atayahmet/laravel-nestable#56]
Merhabalar , ahmet bey öncelikle çok teşekkür ederim controller ve view üzerinden kullanımını anlatabilirmisiniz   Category::nested()->get() yi blade içerisine mi yazacam yoksa Controller içerisine mi ikisinide denedim view de hiç çalışmadı controller kısmına yazdığımda ise aşağıdaki hatayı aldım sürüm olarak laravel 5.4 kullanıyorum yardımcı olursanız sevinirim 

`Undefined index:
--
in NestableService.php line 183`

**Comment by atayahmet** [comment]
Selamlar @GkyKrkc 

Öncelikle kategori tablonuz config'te istendiği şekilde düzenlediğinizden emin olun.
Şuradaki: [Örnek Tablo](https://github.com/atayahmet/laravel-nestable#basic-usage-with-eloquent)

`Menü` ya da `dropdown` gibi bir markup generate etmek istiyorsanız `view` içindeki kullanım için [şu linkte](https://github.com/atayahmet/laravel-nestable#renderasdropdownrenderasmultiple) örnekleri bulabilirsiniz.

Dökümana detaylı bir şekilde göz atmanızda fayda var.

**Comment by GkyKrkc** [comment]
Çok teşekkür ederim, seninle gurur duydum gerçekten, publis yapmayı unutmuşum ondan hata verirmiş :) Allah razı olsun üstadım.
