### ISSUE TITLE
How to display nestable array data in view ?

### ISSUE THREAD

**Issue by DarkcoderSe** [atayahmet/laravel-nestable#58]
![image](https://user-images.githubusercontent.com/25286912/41652806-9e15a3f2-749d-11e8-8be3-bd8aa507979d.png)

i dd() the data. but when i use foreach loop for this data it shows error.
how to solve this ?

**Comment by atayahmet** [comment]
What do you do want to do exactly? If you want to show the data as html markup in view, you can use the `renderAsHtml` or `renderAsDropdown` methods. Or can you share errors stack?
