### ISSUE TITLE
3 level nested?

### ISSUE THREAD

**Issue by zendzo** [atayahmet/laravel-nestable#60]
can i implement 3 levels nested with this package?
looks like example below?

1. mobile & accesory(category)
 -mobile(subcategory)
--iphone(product)

2.electronics(category)
-laptops(subcategory)
--hp(product)

**Comment by atayahmet** [comment]
Hi @zendzo 

Yes, you can but you can not the product link to category link. Take a look [customUrl](https://github.com/atayahmet/laravel-nestable#customurl) for that.
