### ISSUE TITLE
Use package in multiple models

### ISSUE THREAD

**Issue by josegus** [atayahmet/laravel-nestable#69]
![image](https://user-images.githubusercontent.com/13947849/56229098-27e87100-6047-11e9-8281-4b09d14c5cb2.png)

The config options are forcing me to name my foreign key like this value. How can i use this package in different recursive models? I have product, category, an brand models, all of this has product_id, category_id  and brand_id as foreign key.

**Comment by atayahmet** [comment]
Hi @josegus 

Unfortunately there are no this feature.

**Comment by josegus** [comment]
are pull request allowed? I mean, a pull request making this option available. No breaking changes, just extend the actual config.

**Comment by atayahmet** [comment]
I definitely accept. Please add your tests.
