### ISSUE TITLE
how to get only one category children

### ISSUE THREAD

**Issue by ahmadalukah** [atayahmet/laravel-nestable#7]
Hi !
Thank you so much for this amazing resource,

I want to know if there is a way to only render one category with its children.

for example:
- cat1 children are : -cat2 and -cat3
- cat5 no children
- cat4 no children
- cat6 no children

how can I only get cat1 with its children: cat2 and cat3

Thank you.

**Comment by atayahmet** [comment]
Hi @ahmadalukah 

Actually no shortcut to it in package but you can pass native sql query result to `nestable()->make($result)` method. (for now)

I will add this feature next version and create a task about this.
