### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by GlitterCakes** [atayahmet/laravel-nestable#71]
This happens when attempting to use any function (that uses recursion behind the scenes).

Side Note: My database table structure uses UUIDs for the primary key column, and thus also for the parent_id column. I also have a nullable foreign key from parent_id to id to constrain relationships.

The documentation shows a parent_id of "0" for a category that's at the top. In my case, it's simply a null value for parent_id if it's at the top. A value of 0 would error out even if you were using numeric values with a foreign key constraint, as 0 would never be a valid ID because auto incrementing columns typically start on 1.

Not sure what the issue is with this but I'm guessing it has something to do with this.

**Comment by atayahmet** [comment]
Hi @GlitterCakes 

the determinations you have made are very appropriate but they should not have anything to do with the error. This is due to php's recursive limits. What is your php version?

**Comment by GlitterCakes** [comment]
Well, it works fine when I write the recursive handler myself on the same dataset. So there is a problem with the package. This is on PHP version 7.3.

**Comment by atayahmet** [comment]
Hi @GlitterCakes 

glad to work that.
