### ISSUE TITLE
Call to a member function delete() on null in NestableTrait

### ISSUE THREAD

**Issue by Sarav-S** [atayahmet/laravel-nestable#8]
When I try deleting a record, it is throwing me this error

```
FatalErrorException in NestableTrait.php line 277:
Call to a member function delete() on null
```

My Model File

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nestable\NestableTrait;

class Menu extends Model
{
use NestableTrait;

protected $parent = 'parent_id';

protected $fillable = ['parent_id', 'menu_id', 'name', 'slug', 'status'];
}
```

**Comment by atayahmet** [comment]
Hi @Sarav-S 

It worked well in my test as follows.

```php
Category::where('id', 1)->delete();
```

```php
$category = new Category;

$category->newInstance()->where('id', 2)->delete();

```

Is there any example code?

**Comment by Sarav-S** [comment]
Hi @atayahmet 

    Category::where('id', 1)->delete();// this works.

But I have trying to delete by following code

    $category = Category::find($id); 
    // Perform some logic and then
    $category->delete()

**Comment by atayahmet** [comment]
Hi @Sarav-S 

i fixed it. Please update package.

**Comment by Sarav-S** [comment]
@atayahmet Great! Will package now. 👍
